"""M1: graph statistics report -> docs/m1-report.md.

Degree histograms are rendered as text (log-spaced bins, log-scaled bars)
because matplotlib is not an approved dependency (m1-brief.md allows this).

Usage: python -m flysim.graph.stats
"""
from __future__ import annotations

import json
import sys
import time

import numpy as np

from ..data.download import ROOT
from .build import BUILD_LOG
from .constants import NT_CODES, NT_SIGN, SIDE_CODES
from .graph import Graph

REPORT = ROOT / "docs" / "m1-report.md"
# Verified in docs/annotations-observed.md / m1-brief.md.
EXAMPLE_TYPE = "DNp01"


def text_hist(values: np.ndarray, title: str, width: int = 50) -> str:
    """Log-spaced bins on the value axis, log-scaled bar length on the count axis."""
    v = values.astype(np.int64)
    n_zero = int((v == 0).sum())
    nz = v[v > 0]
    edges = np.unique(np.concatenate([[1], np.logspace(0, np.log10(nz.max() + 1), 20).astype(np.int64) + 0, [nz.max() + 1]]))
    counts, _ = np.histogram(nz, bins=edges)
    lmax = np.log10(max(counts.max(), n_zero, 1) + 1)
    lines = [f"{title}  (n={len(v):,}, zero={n_zero:,}, max={nz.max():,}, "
             f"mean={v.mean():.1f}, median={np.median(v):.0f})", "",
             "```", f"{'degree range':>16} {'count':>9}  bar (log10 scale)", f"{'-'*16} {'-'*9}  {'-'*width}"]
    bar = "#" * int(round(width * np.log10(n_zero + 1) / lmax))
    lines.append(f"{'0':>16} {n_zero:>9}  {bar}")
    for lo, hi, c in zip(edges[:-1], edges[1:], counts):
        label = f"{lo}" if hi - lo == 1 else f"{lo}–{hi-1}"
        bar = "#" * int(round(width * np.log10(c + 1) / lmax))
        lines.append(f"{label:>16} {c:>9}  {bar}")
    lines.append("```")
    return "\n".join(lines)


def main() -> int:
    t0 = time.time()
    g = Graph.load()
    t_load = time.time() - t0
    st = g.stats()
    build = json.loads(BUILD_LOG.read_text()) if BUILD_LOG.exists() else {}
    outd, ind = g.out_degree(), g.in_degree()
    abs_w = np.abs(g.weight).astype(np.int64)

    # shortest path timing on the two DNp01 neurons (L/R)
    ex = g.query.by_type(EXAMPLE_TYPE)
    a, b = int(g.body(ex[0])), int(g.body(ex[1]))
    t1 = time.time()
    path = g.shortest_path(a, b)
    t_sp = time.time() - t1
    desc = g.query.describe(g.idx(np.array(path)))

    sides = {k: int((g.side == v).sum()) for k, v in SIDE_CODES.items()} | {"null": int((g.side == -1).sum())}
    L = []
    L.append("# M1 report — CSR graph + annotation query API\n")
    L.append(f"Generated by `python -m flysim.graph.stats` on {time.strftime('%Y-%m-%d %H:%M %z')}. "
             f"Build log: `data-provenance/m1-build.json`; sign counts: `data-provenance/edge-signs.md`.\n")
    L.append("## Retained graph\n")
    L.append("Retention rule: `annotations.status == \"Traced\"`, edges with both endpoints retained, "
             "no weight threshold (data-provenance/retention.md).\n")
    L.append("| item | value |\n|---|---|")
    L.append(f"| neurons | {st.n_neurons:,} |")
    L.append(f"| directed edges | {st.n_edges:,} |")
    L.append(f"| synaptic contacts | {st.contacts_total:,} |")
    L.append(f"| self loops (raw file had 123) | {st.n_self_loops:,} |")
    L.append(f"| neurons with out-degree 0 | {int((outd == 0).sum()):,} |")
    L.append(f"| neurons with in-degree 0 | {int((ind == 0).sum()):,} |")
    L.append(f"| isolated (both 0) | {int(((outd == 0) & (ind == 0)).sum()):,} |")
    L.append(f"| side L / R / M / null | {sides['L']:,} / {sides['R']:,} / {sides['M']:,} / {sides['null']:,} |")
    L.append(f"| side from instance suffix (somaSide null) | {build.get('neurons', {}).get('side_from_instance_suffix', 'n/a'):,} |")
    L.append(f"| soma_xyz present | {int(g.has_soma_xyz.sum()):,} |")
    L.append(f"| edge weight (contacts) max / mean / median | {abs_w.max():,} / {abs_w.mean():.2f} / {np.median(abs_w):.0f} |")
    L.append("")

    L.append("## Edge signs\n")
    L.append("Sign = presynaptic neuron's `consensus_nt` (Dale's principle, **assumption**). "
             "Rows marked *assumption* follow the approved rule in `data-provenance/edge-signs.md`.\n")
    L.append("| pre consensus_nt | sign | neurons | edges | contacts | basis |\n|---|---|---|---|---|---|")
    for name, code in NT_CODES.items():
        s = build.get("edges_by_pre_nt", {}).get(name, {})
        basis = ("assumption" if s.get("assumed") else "standard") + (", modulator mask" if s.get("modulator") else "")
        L.append(f"| {name} | {int(NT_SIGN[code]):+d} | {int((g.nt == code).sum()):,} | "
                 f"{s.get('edges', 0):,} | {s.get('contacts', 0):,} | {basis} |")
    L.append(f"| **excitatory total** | +1 | | {st.edges_excitatory:,} | {st.contacts_excitatory:,} | |")
    L.append(f"| **inhibitory total** | −1 | | {st.edges_inhibitory:,} | {st.contacts_inhibitory:,} | |")
    L.append(f"\nNeurons whose sign rests on an assumption: {int(g.nt_assumed.sum()):,} "
             f"(`nt_assumed` mask); modulator-flagged: {int(g.nt_modulator.sum()):,} (`nt_modulator` mask).")
    miss = g.nt == NT_CODES["missing"]
    L.append(f"Observed: the {int(miss.sum()):,} retained neurons absent from the NT table have "
             f"{int(outd[miss].sum()):,} outgoing edges in total (in-degree sum {int(ind[miss].sum()):,}), "
             f"so the +1 assumption for them currently affects no edge.\n")

    L.append("## Degree distributions (text histograms; matplotlib not installed)\n")
    L.append(text_hist(outd, "Out-degree (distinct postsynaptic partners)"))
    L.append("")
    L.append(text_hist(ind, "In-degree (distinct presynaptic partners)"))
    L.append("")

    L.append("## Memory\n")
    L.append("| array | dtype | shape | bytes |\n|---|---|---|---|")
    for k, v in g._arrays.items():
        L.append(f"| `{k}` | {v.dtype} | {v.shape} | {v.nbytes:,} |")
    L.append(f"| **total** | | | **{st.cache_bytes:,}** ({st.cache_bytes/2**20:.0f} MiB) |")
    L.append(f"\nForward CSR alone (indptr+indices+weight): "
             f"{g.indptr.nbytes + g.indices.nbytes + g.weight.nbytes:,} bytes; the CSC copy doubles that. "
             f"Fits the CLAUDE.md §2 budget (full graph resident on a 16 GB GPU).\n")

    L.append("## Timing\n")
    L.append("| step | seconds |\n|---|---|")
    for k, v in build.get("timings_s", {}).items():
        L.append(f"| build: {k} | {v} |")
    L.append(f"| Graph.load() from cache | {t_load:.2f} |")
    L.append(f"| shortest_path({a}, {b}) | {t_sp*1000:.1f} ms |")
    L.append("")

    L.append(f"## Example: shortest path between the two `{EXAMPLE_TYPE}` neurons\n")
    L.append(f"`shortest_path({a}, {b})` → {len(path)-1} hops (unweighted BFS, directed):\n")
    L.append("| hop | bodyId | type | instance | somaSide |\n|---|---|---|---|---|")
    for i, (_, r) in enumerate(desc.iterrows()):
        L.append(f"| {i} | {r.bodyId} | {r.type} | {r.instance} | {r.somaSide} |")
    L.append("")
    L.append("## Acceptance (CLAUDE.md §6 M1)\n")
    L.append("- [x] shortest path between arbitrary neurons (`Graph.shortest_path`, raises `NoPathError` if none)")
    L.append(f"- [x] `query.by_type(\"{EXAMPLE_TYPE}\")` returns {ex.size} neurons; unknown names raise `LookupError` (tests/test_graph.py)")
    L.append("- [x] in/out-degree histograms (above)")
    L.append("- [x] `pytest tests/` passes")
    L.append("")
    REPORT.write_text("\n".join(L))
    print(f"report written to {REPORT.relative_to(ROOT)} in {time.time()-t0:.1f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
