"""M6a tests: SWC parsing, branch-preserving decimation and bundle output.

Everything here runs on synthetic skeletons and a stub graph — no network, no
downloaded data — so the suite stays fast and deterministic. The contract under
test is docs/m6-3d-contract.md "파일 2"; the pipeline is docs/m6a-brief.md.
"""
import json

import numpy as np
import pytest

from flysim.data import skeletons as sk


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def swc(lines: str) -> str:
    """SWC text with the header comments the real files carry."""
    return ("#Generated by NeuTu (https://github.com/janelia-flyem/NeuTu)\n"
            '#${"ds_intv": [63, 63, 63]}\n\n' + lines)


def straight_line(n: int = 11, step: float = 100.0) -> str:
    """One straight chain along +x: RDP must collapse it to a single segment."""
    out = []
    for i in range(n):
        out.append(f"{i+1} 0 {i*step} 0 0 1 {i if i else -1}")
    return swc("\n".join(out) + "\n")


def forked() -> str:
    """A 'Y': trunk 1-2-3, then two branches. Node 3 is the branch point.

        1 - 2 - 3 - 4 - 5        (+x)
                  \\- 6 - 7       (+y)

    Three branch paths (trunk 1-2-3, arm 3-4-5, arm 3-6-7), so the decimation
    floor is 3 segments however large the tolerance.
    """
    return swc(
        "1 0 0 0 0 1 -1\n"
        "2 0 100 0 0 1 1\n"
        "3 0 200 0 0 1 2\n"
        "4 0 300 0 0 1 3\n"
        "5 0 400 0 0 1 4\n"
        "6 0 200 100 0 1 3\n"
        "7 0 200 200 0 1 6\n")


class StubGraph:
    """Minimal duck-type of flysim.graph.Graph for the bundle tests."""

    def __init__(self, body_ids, soma=None):
        self.body_ids = np.asarray(body_ids, dtype=np.int64)
        n = len(self.body_ids)
        self.soma_xyz = np.full((n, 3), np.nan, dtype=np.float32)
        self.has_soma_xyz = np.zeros(n, dtype=bool)
        for i, v in (soma or {}).items():
            self.soma_xyz[i] = v
            self.has_soma_xyz[i] = True

    def idx(self, body_id):
        b = np.atleast_1d(np.asarray(body_id, dtype=np.int64))
        pos = np.searchsorted(self.body_ids, b)
        if (self.body_ids[np.minimum(pos, len(self.body_ids) - 1)] != b).any():
            raise KeyError("bodyId not in stub graph")
        return pos

    def body(self, idx):
        return self.body_ids[idx]


@pytest.fixture
def patched_download(monkeypatch, tmp_path):
    """Route downloads to files written into tmp_path; no network."""
    store: dict[int, str] = {}

    def fake(body_id, prov, force=False):
        body_id = int(body_id)
        if body_id not in store:
            return None, "missing"
        p = tmp_path / f"{body_id}.swc"
        p.write_text(store[body_id])
        prov[f"{body_id}.swc"] = {"md5": "stub", "bytes": len(store[body_id])}
        return p, "downloaded"

    monkeypatch.setattr(sk, "download_skeleton", fake)
    monkeypatch.setattr(sk, "_save_provenance", lambda p: None)
    monkeypatch.setattr(sk, "_load_provenance", lambda: {})
    return store


# ---------------------------------------------------------------------------
# parsing
# ---------------------------------------------------------------------------
def test_parse_swc_columns_and_comments():
    n = sk.parse_swc(forked())
    assert len(n["id"]) == 7
    assert n["id"].tolist() == [1, 2, 3, 4, 5, 6, 7]
    assert n["parent"].tolist() == [-1, 1, 2, 3, 4, 3, 6]
    assert n["xyz"].shape == (7, 3)
    assert n["xyz"][4].tolist() == [400.0, 0.0, 0.0]
    assert n["xyz"].dtype == np.float64          # voxels, written through unchanged
    assert n["radius"].tolist() == [1.0] * 7


def test_parse_swc_rejects_short_rows_and_empty_files():
    with pytest.raises(ValueError, match="7 columns"):
        sk.parse_swc(swc("1 0 0 0 0 1\n"))
    with pytest.raises(ValueError, match="no nodes"):
        sk.parse_swc(swc(""))


def test_parse_swc_accepts_a_path(tmp_path):
    p = tmp_path / "x.swc"
    p.write_text(forked())
    assert len(sk.parse_swc(p)["id"]) == 7
    assert len(sk.parse_swc(str(p))["id"]) == 7


def test_forest_multiple_roots_and_dangling_parent():
    """Two roots, and a parent id that is not in the file, both start trees."""
    n = sk.parse_swc(swc("1 0 0 0 0 1 -1\n2 0 100 0 0 1 1\n"
                         "3 0 0 500 0 1 -1\n4 0 100 500 0 1 3\n"
                         "5 0 0 900 0 1 999\n6 0 100 900 0 1 5\n"))
    paths, n_branch, n_roots = sk.branch_paths(n["id"], n["parent"])
    assert n_roots == 3 and n_branch == 0
    assert len(paths) == 3


def test_cycle_is_rejected():
    n = sk.parse_swc(swc("1 0 0 0 0 1 3\n2 0 100 0 0 1 1\n3 0 200 0 0 1 2\n"))
    with pytest.raises(ValueError, match="cycle"):
        sk.branch_paths(n["id"], n["parent"])


# ---------------------------------------------------------------------------
# decimation: branch preservation and tolerance
# ---------------------------------------------------------------------------
def test_straight_line_collapses_to_one_segment():
    res = sk.simplify_neuron(sk.parse_swc(straight_line(11, 100.0)), tolerance=40.0)
    assert res["n_nodes_raw"] == 11
    assert res["n_branch_points"] == 0 and res["n_roots"] == 1
    assert len(res["segments"]) == 1
    assert res["segments"][0][0].tolist() == [0.0, 0.0, 0.0]
    assert res["segments"][0][1].tolist() == [1000.0, 0.0, 0.0]


def test_branch_points_and_endpoints_are_preserved():
    """Even at a tolerance far larger than the neuron, the Y keeps its fork."""
    res = sk.simplify_neuron(sk.parse_swc(forked()), tolerance=1e6, max_segments=10_000)
    assert res["n_branch_points"] == 1
    assert len(res["segments"]) == res["segment_floor"] == 3
    pts = res["segments"].reshape(-1, 3)
    for required in ([200.0, 0.0, 0.0],        # the branch point
                     [400.0, 0.0, 0.0],        # endpoint of branch 1
                     [200.0, 200.0, 0.0],      # endpoint of branch 2
                     [0.0, 0.0, 0.0]):         # the root
        assert any(np.array_equal(p, required) for p in pts), required


def test_tolerance_is_respected():
    """A point displaced by d is kept when d > tol and dropped when d < tol."""
    d = 50.0
    text = swc(f"1 0 0 0 0 1 -1\n2 0 100 {d} 0 1 1\n3 0 200 0 0 1 2\n")
    n = sk.parse_swc(text)
    keep_tight, dev_tight = sk.rdp_mask(n["xyz"], d / 2)
    keep_loose, dev_loose = sk.rdp_mask(n["xyz"], d * 2)
    assert keep_tight.tolist() == [True, True, True]
    assert keep_loose.tolist() == [True, False, True]
    assert dev_tight == 0.0                      # nothing dropped
    assert dev_loose == pytest.approx(d)         # the dropped point's deviation
    assert dev_loose <= d * 2                    # never exceeds the tolerance


def test_reported_max_deviation_never_exceeds_tolerance():
    rng = np.random.default_rng(0)
    pts = np.cumsum(rng.normal(0, 30, size=(400, 3)), axis=0)
    for tol in (5.0, 40.0, 200.0):
        keep, dev = sk.rdp_mask(pts, tol)
        assert dev <= tol + 1e-9
        assert keep[0] and keep[-1]
        # The RDP guarantee, checked point by point: every dropped point lies
        # within tol of the infinite line through the retained pair that brackets
        # it (that pair is exactly the span the recursion accepted). Note this is
        # NOT the clamped distance to the nearest retained segment, which classic
        # RDP does not bound and which can legitimately exceed tol.
        kept_idx = np.flatnonzero(keep)
        for i in np.flatnonzero(~keep):
            a = pts[kept_idx[kept_idx < i][-1]]
            b = pts[kept_idx[kept_idx > i][0]]
            assert _line_distance(pts[i], a, b) <= tol + 1e-6
    # a looser tolerance never keeps more points
    counts = [int(sk.rdp_mask(pts, t)[0].sum()) for t in (5.0, 40.0, 200.0)]
    assert counts == sorted(counts, reverse=True)


def _line_distance(p, a, b):
    """Perpendicular distance from p to the infinite line through a and b."""
    s = b - a
    l2 = float(s @ s)
    if l2 <= 0:
        return float(np.linalg.norm(p - a))
    return float(np.linalg.norm((p - a) - ((p - a) @ s / l2) * s))


def test_segment_cap_raises_tolerance_and_stops_at_the_branch_floor():
    """A 100-node zigzag exceeds a cap of 5 at tol 1, so the tolerance is raised."""
    pts = [(i * 100.0, (i % 2) * 300.0, 0.0) for i in range(100)]
    text = swc("\n".join(f"{i+1} 0 {x} {y} {z} 1 {i if i else -1}"
                         for i, (x, y, z) in enumerate(pts)) + "\n")
    n = sk.parse_swc(text)
    loose = sk.simplify_neuron(n, tolerance=1.0, max_segments=5)
    assert loose["tolerance_steps"] > 0
    assert loose["tolerance_voxels"] > 1.0
    assert len(loose["segments"]) <= 5 and loose["cap_met"]
    # an unbranched chain can always reach 1 segment, so the floor is not binding here
    assert loose["segment_floor"] == 1


def test_cap_below_the_branch_floor_is_reported_not_faked():
    """The floor is one segment per branch path; RDP cannot go below it, and the
    result says so rather than pruning branches to fit (docs/m6a-report.md)."""
    res = sk.simplify_neuron(sk.parse_swc(forked()), tolerance=40.0, max_segments=1)
    assert res["segment_floor"] == 3
    assert len(res["segments"]) == 3             # branch points still preserved
    assert res["cap_met"] is False
    assert res["n_branch_points"] == 1


# ---------------------------------------------------------------------------
# bundle output (contract file 2)
# ---------------------------------------------------------------------------
CONTRACT_TOP_KEYS = {"set", "voxel_nm", "n_neurons", "n_segments", "bbox", "decimation",
                     "neurons", "missing", "source", "generated"}
CONTRACT_NEURON_KEYS = {"body_id", "idx", "seg_offset", "seg_count", "soma", "n_nodes_raw"}


def test_bundle_json_has_every_contract_key(patched_download, tmp_path):
    patched_download[100] = forked()
    patched_download[200] = straight_line()
    g = StubGraph([100, 200], soma={0: (1.0, 2.0, 3.0)})
    bin_path, json_path = sk.build_bundle([100, 200], "T", graph=g, out_dir=tmp_path,
                                          max_segments_per_neuron=10_000, progress=False)
    meta = json.loads(json_path.read_text())
    assert CONTRACT_TOP_KEYS <= set(meta)
    assert meta["set"] == "T" and meta["voxel_nm"] == 8 and meta["n_neurons"] == 2
    assert set(meta["bbox"]) == {"min", "max"} and len(meta["bbox"]["min"]) == 3
    assert meta["decimation"]["method"] == "rdp-per-branch"
    assert {"tolerance_voxels", "max_segments_per_neuron"} <= set(meta["decimation"])
    assert meta["source"]["url_prefix"] == sk.URL_PREFIX
    assert meta["source"]["md5_manifest"] == "data-provenance/skeleton-hashes.json"
    for rec in meta["neurons"]:
        assert CONTRACT_NEURON_KEYS <= set(rec)
    assert meta["neurons"][0]["soma"] == [1.0, 2.0, 3.0]
    assert meta["neurons"][1]["soma"] is None


def test_bundle_bin_matches_json_offsets(patched_download, tmp_path):
    patched_download[100] = forked()
    patched_download[200] = straight_line()
    g = StubGraph([100, 200])
    bin_path, json_path = sk.build_bundle([100, 200], "T", graph=g, out_dir=tmp_path,
                                          max_segments_per_neuron=10_000, progress=False)
    meta = json.loads(json_path.read_text())
    buf = np.frombuffer(bin_path.read_bytes(), dtype=np.float32)
    assert buf.size == meta["n_segments"] * 6           # x1 y1 z1 x2 y2 z2
    assert sum(r["seg_count"] for r in meta["neurons"]) == meta["n_segments"]
    off = 0
    for r in meta["neurons"]:                           # offsets are contiguous, in order
        assert r["seg_offset"] == off
        off += r["seg_count"]
    # the straight-line neuron's single segment survives the round trip
    r = [x for x in meta["neurons"] if x["body_id"] == 200][0]
    seg = buf[r["seg_offset"] * 6:(r["seg_offset"] + r["seg_count"]) * 6]
    assert seg.tolist() == [0.0, 0.0, 0.0, 1000.0, 0.0, 0.0]
    assert meta["neurons"][0]["idx"] < meta["neurons"][1]["idx"]   # graph-index order


def test_bundle_drops_body_ids_absent_from_the_graph(patched_download, tmp_path):
    patched_download[100] = forked()
    patched_download[999] = forked()
    g = StubGraph([100, 200])                            # 999 is not a graph neuron
    _, json_path = sk.build_bundle([100, 999], "T", graph=g, out_dir=tmp_path,
                                   max_segments_per_neuron=10_000, progress=False)
    meta = json.loads(json_path.read_text())
    assert [r["body_id"] for r in meta["neurons"]] == [100]
    assert meta["not_in_graph"] == [999]
    with pytest.raises(LookupError, match="retained graph"):
        sk.build_bundle([999], "T2", graph=g, out_dir=tmp_path, progress=False)


def test_missing_skeleton_is_listed_not_skipped_silently(patched_download, tmp_path):
    patched_download[100] = forked()                     # 200 has no skeleton -> 404
    g = StubGraph([100, 200])
    _, json_path = sk.build_bundle([100, 200], "T", graph=g, out_dir=tmp_path,
                                   max_segments_per_neuron=10_000, progress=False)
    meta = json.loads(json_path.read_text())
    assert meta["missing"] == [200]
    assert [r["body_id"] for r in meta["neurons"]] == [100]
    assert meta["n_neurons"] == 1


def test_bundle_over_20mb_raises(patched_download, tmp_path, monkeypatch):
    """Contract: a bundle above 20 MB is an exception, with guidance in the message."""
    patched_download[100] = straight_line()
    g = StubGraph([100])
    monkeypatch.setattr(sk, "MAX_BUNDLE_BYTES", 12)      # one segment = 24 bytes
    with pytest.raises(sk.SkeletonBundleTooLarge) as e:
        sk.build_bundle([100], "T", graph=g, out_dir=tmp_path, progress=False)
    assert "ceiling" in str(e.value) and "max_segments_per_neuron" in str(e.value)
    assert not (tmp_path / "skel-T.bin").exists()        # nothing written on failure


def test_empty_request_raises(tmp_path):
    with pytest.raises(ValueError, match="no bodyIds"):
        sk.build_bundle([], "T", graph=StubGraph([1]), out_dir=tmp_path, progress=False)


def test_unknown_probe_set_name_raises():
    class PS:
        names = ["JO_AB_L", "JO_AB_R", "rest"]
        members = {"JO_AB_L": np.array([0]), "JO_AB_R": np.array([1]), "rest": np.array([2])}
    g = StubGraph([10, 20, 30])
    assert sk.probe_set_body_ids(g, "JO_AB", ps=PS()).tolist() == [10, 20]
    with pytest.raises(LookupError, match="unknown probe set"):
        sk.probe_set_body_ids(g, "NOPE", ps=PS())


def test_server_md5_header_parsing():
    class H:
        def get_all(self, k):
            return ["crc32c=av9IGg==", "md5=kwhN0kYXTGMgb/WKuU+Rkw=="]
    # the real header observed for bodyId 98113
    assert sk._server_md5(H()) == "93084dd246174c63206ff58ab94f9193"

    class NoMd5:
        def get_all(self, k):
            return ["crc32c=av9IGg=="]
    assert sk._server_md5(NoMd5()) is None
