"""M0: convert raw feather files to parquet and record observed annotation values.

No filtering happens here. The full tables are converted 1:1 so every later
filter (graph retention etc.) is explicit and logged in the graph module.
Also writes docs/annotations-observed.md from the actual data so that no
column name or category value in this codebase is typed from memory.

Usage: python -m flysim.data.convert
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

import pandas as pd
import pyarrow.feather as pf
import pyarrow.parquet as pq

from .download import CORE_FILES, RAW_DIR, ROOT

PARQUET_DIR = ROOT / "data" / "parquet"
OBSERVED_DOC = ROOT / "docs" / "annotations-observed.md"

# Categorical columns whose full value set is small enough to list verbatim.
ANN_CATEGORICAL = [
    "status", "statusLabel", "superclass", "class", "somaSide", "rootSide",
    "fruDsx", "dimorphism", "somaNeuromere", "entryNerve", "exitNerve",
    "receptorType", "birthtime", "itoleeHl", "trumanHl",
]
NT_CATEGORICAL = ["predicted_nt", "consensus_nt", "celltype_predicted_nt", "ground_truth"]


def convert_one(key: str) -> Path:
    src = RAW_DIR / CORE_FILES[key]
    dst = PARQUET_DIR / f"{key}.parquet"
    PARQUET_DIR.mkdir(parents=True, exist_ok=True)
    t0 = time.time()
    table = pf.read_table(src)
    pq.write_table(table, dst, compression="zstd")
    print(f"[conv] {key}: {table.num_rows} rows, {len(table.schema)} cols -> {dst.name} "
          f"({dst.stat().st_size/1e6:.0f} MB, {time.time()-t0:.1f}s)")
    return dst


def _vc_md(s: pd.Series, limit: int = 40) -> str:
    v = s.value_counts(dropna=False)
    lines = ["| value | count |", "|---|---|"]
    for k, n in v.head(limit).items():
        label = "(null)" if pd.isna(k) else str(k)
        lines.append(f"| `{label}` | {n} |")
    if v.size > limit:
        lines.append(f"| … {v.size - limit} more | |")
    return "\n".join(lines)


def write_observed_doc() -> None:
    ann = pq.read_table(PARQUET_DIR / "annotations.parquet").to_pandas()
    nt = pq.read_table(PARQUET_DIR / "neurotransmitters.parquet").to_pandas()
    w_schema = pq.read_schema(PARQUET_DIR / "weights.parquet")

    out = [
        "# Observed annotation columns and values (auto-generated)",
        "",
        f"Generated by `python -m flysim.data.convert` on {time.strftime('%Y-%m-%d')} from "
        "MaleCNS v1.0 flat-connectome files. **Do not edit by hand.** Every identifier used in "
        "code must appear here.",
        "",
        "## body-annotations (`annotations.parquet`)",
        f"rows: {len(ann)}  ·  bodyId unique: {ann.bodyId.is_unique}",
        "",
        "### Columns",
        "| column | dtype | non-null | unique |", "|---|---|---|---|",
    ]
    for c in ann.columns:
        s = ann[c]
        try:
            nun = s.nunique()
        except TypeError:  # list column
            nun = "n/a"
        out.append(f"| `{c}` | {s.dtype} | {s.notna().sum()} | {nun} |")
    out += ["", "### Categorical value counts (whole table, all statuses)"]
    for c in ANN_CATEGORICAL:
        out += ["", f"#### `{c}`", _vc_md(ann[c])]
    out += [
        "",
        "### `type` (cell type) — too many to list",
        f"non-null: {ann['type'].notna().sum()}, unique: {ann['type'].nunique()}. "
        "Query by exact string via the graph annotation API; it raises on 0 matches.",
        "",
        "## body-neurotransmitters (`neurotransmitters.parquet`)",
        f"rows: {len(nt)}  ·  body unique: {nt.body.is_unique}",
        "",
        "Columns: " + ", ".join(f"`{c}`" for c in nt.columns),
    ]
    for c in NT_CATEGORICAL:
        out += ["", f"#### `{c}`", _vc_md(nt[c])]
    out += [
        "",
        "## connectome-weights (`weights.parquet`)",
        "Columns: " + ", ".join(f"`{f.name}` ({f.type})" for f in w_schema),
        "",
        "`weight` = number of synaptic contacts (pre→post) at min confidence 0.5. "
        "One row per (body_pre, body_post) pair; no duplicate pairs.",
    ]
    OBSERVED_DOC.parent.mkdir(parents=True, exist_ok=True)
    OBSERVED_DOC.write_text("\n".join(out) + "\n")
    print(f"[doc ] wrote {OBSERVED_DOC.relative_to(ROOT)}")


def main() -> int:
    for k in CORE_FILES:
        convert_one(k)
    write_observed_doc()
    return 0


if __name__ == "__main__":
    sys.exit(main())
