"""Per-neuron ROI (neuropil) assignment and synapse centroid from syn-partners.

Reads syn-partners-*.feather batch by batch (312M rows) and, for every
retained neuron (status == "Traced", same rule as the graph), accumulates
  - number of synaptic sites (pre + post) per `primary_post` ROI label,
  - centroid of all its synaptic sites (pre and post) in voxel coords.

`primary_post` is the ROI of the postsynaptic site; we attribute the same ROI
to the presynaptic site of that row (**assumption**: a synaptic contact lies
in one neuropil). Output:
  data/cache/neuron-roi-v1.parquet   one row per retained neuron
  data-provenance/roi-observed.md    the ROI label set and totals (auto-generated)

Usage: python -m flysim.data.roi
"""
from __future__ import annotations

import sys
import time

import numpy as np
import pandas as pd
import pyarrow.ipc as ipc
import pyarrow.parquet as pq

from .convert import PARQUET_DIR
from .download import ALL_FILES, RAW_DIR, ROOT

SRC = RAW_DIR / ALL_FILES["syn_partners"]
OUT = ROOT / "data" / "cache" / "neuron-roi-v1.parquet"
DOC = ROOT / "data-provenance" / "roi-observed.md"
RETAIN_STATUS = "Traced"


def main() -> int:
    ann = pq.read_table(PARQUET_DIR / "annotations.parquet", columns=["bodyId", "status"]).to_pandas()
    body_ids = np.sort(ann.loc[ann.status == RETAIN_STATUS, "bodyId"].to_numpy())
    n = len(body_ids)
    f = ipc.open_file(SRC)
    labels = f.get_batch(0).column("primary_post").dictionary.to_pylist()
    L = len(labels)
    print(f"retained neurons={n}, batches={f.num_record_batches}, roi labels={L}")

    counts = np.zeros((n, L), dtype=np.int32)          # sites per ROI (pre+post)
    csum = np.zeros((n, 3), dtype=np.float64)           # centroid accumulator
    csn = np.zeros(n, dtype=np.int64)
    n_pre_sites = np.zeros(n, dtype=np.int64)
    n_post_sites = np.zeros(n, dtype=np.int64)
    rows = 0
    t0 = time.time()

    def lookup(b):
        pos = np.searchsorted(body_ids, b)
        pos[pos == n] = 0
        return pos, body_ids[pos] == b

    for k in range(f.num_record_batches):
        b = f.get_batch(k)
        rows += b.num_rows
        roi = b.column("primary_post").indices.to_numpy(zero_copy_only=False).astype(np.int64)
        assert b.column("primary_post").dictionary.to_pylist() == labels, "dictionary changed between batches"
        for side, xyz in (("pre", ("x_pre", "y_pre", "z_pre")), ("post", ("x_post", "y_post", "z_post"))):
            bid = b.column(f"body_{side}").to_numpy()
            pos, ok = lookup(bid)
            if not ok.any():
                continue
            p = pos[ok]
            np.add.at(counts, (p, roi[ok]), 1)
            xyzs = np.stack([b.column(c).to_numpy()[ok] for c in xyz], axis=1).astype(np.float64)
            np.add.at(csum, p, xyzs)
            np.add.at(csn, p, 1)
            np.add.at(n_pre_sites if side == "pre" else n_post_sites, p, 1)
        if k % 500 == 0:
            print(f"  batch {k}/{f.num_record_batches} rows={rows/1e6:.0f}M {time.time()-t0:.0f}s", flush=True)

    tot = counts.sum(axis=1)
    dom = counts.argmax(axis=1)
    dom_frac = np.where(tot > 0, counts[np.arange(n), dom] / np.maximum(tot, 1), np.nan)
    centroid = np.where(csn[:, None] > 0, csum / np.maximum(csn, 1)[:, None], np.nan)

    df = pd.DataFrame({
        "bodyId": body_ids,
        "n_sites": tot,
        "n_pre_sites": n_pre_sites,
        "n_post_sites": n_post_sites,
        "primary_roi": pd.Categorical.from_codes(dom, labels),
        "primary_roi_frac": dom_frac,
        "cx": centroid[:, 0], "cy": centroid[:, 1], "cz": centroid[:, 2],
    })
    df.loc[tot == 0, "primary_roi"] = np.nan
    OUT.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(OUT, index=False)
    # full per-ROI count matrix as a second file (for probes that need all ROIs of a neuron)
    pq.write_table(
        pd.DataFrame(counts, columns=labels).assign(bodyId=body_ids).pipe(lambda d: __import__("pyarrow").Table.from_pandas(d, preserve_index=False)),
        OUT.with_name("neuron-roi-counts-v1.parquet"), compression="zstd")

    roi_tot = pd.Series(counts.sum(axis=0), index=labels).sort_values(ascending=False)
    lines = [
        "# ROI labels observed in syn-partners `primary_post` (auto-generated)", "",
        f"Generated by `python -m flysim.data.roi` on {time.strftime('%Y-%m-%d')}. Rows scanned: {rows:,}. "
        f"Retained neurons: {n:,}; with ≥1 site: {(tot>0).sum():,}; with no site: {(tot==0).sum():,}.",
        "", "**Note:** there is no `AMMC` label. Auditory-relevant labels present: `SAD`, `WED(L)`, `WED(R)`, `GNG`, `AVLP(L/R)`.",
        "", "| primary_post | sites (retained neurons, pre+post) |", "|---|---|",
    ] + [f"| `{k}` | {v:,} |" for k, v in roi_tot.items()]
    DOC.write_text("\n".join(lines) + "\n")
    print(f"done in {time.time()-t0:.0f}s; wrote {OUT.name}, {OUT.with_name('neuron-roi-counts-v1.parquet').name}, {DOC.name}")
    print("neurons without any synapse site:", int((tot == 0).sum()))
    print(df.primary_roi.value_counts().head(20).to_string())
    return 0


if __name__ == "__main__":
    sys.exit(main())
